### ISSUE TITLE
Android crashing (NoClassDefFoundError)

### ISSUE THREAD

**Issue by CmerCy132** [react-native-kit/react-native-track-player#1049]
**Describe the bug**
I am getting this error when trying to use the package on android:

java.lang.NoClassDefFoundError: Failed resolution of: Lfm/indiecast/rnaudiostreamer/RNAudioStreamerModule;
        at fm.indiecast.rnaudiostreamer.RNAudioStreamerPackage.createNativeModules(RNAudioStreamerPackage.java:21)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: fm.indiecast.rnaudiostreamer.RNAudioStreamerModule
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at fm.indiecast.rnaudiostreamer.RNAudioStreamerPackage.createNativeModules(RNAudioStreamerPackage.java:21) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225) 
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayer$EventListener;

**Environment (please complete the following information):**
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 41.98 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.3, 29.0.2, 30.0.0, 30.0.2
      System Images: android-27 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.2/12B5018i - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_162 - /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

What `react-native-track-player` version are you using?
"react-native-track-player": "^1.2.3",

I'm also using
"react-native-video": "^4.4.5",

Are you testing on a real device or in the simulator? Which OS version are you running?
Android Emulator (8.1.0)
Samsung A30 (10.0)

**Code**
TrackPlayer.setupPlayer()

**Comment by CmerCy132** [comment]
I noticed that there was a duplicate package on my package.json

closing this ticket
