### ISSUE TITLE
PlayerService has leaked IntentReceiver

### ISSUE THREAD

**Issue by puckey** [react-native-kit/react-native-track-player#115]
I am seeing the following error in logcat:

```17:05:13 E ActivityThread : Service guichaguri.trackplayer.logic.services.PlayerService has leaked IntentReceiver guichaguri.trackplayer.metadata.components.NoisyReceiver@d603de8 that was originally registered here. Are you missing a call to unregisterReceiver()?
17:05:13 E ActivityThread : android.app.IntentReceiverLeaked: Service guichaguri.trackplayer.logic.services.PlayerService has leaked IntentReceiver guichaguri.trackplayer.metadata.components.NoisyReceiver@d603de8 that was originally registered here. Are you missing a call to unregisterReceiver()?
17:05:13 E ActivityThread : at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1222)
17:05:13 E ActivityThread : at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:993)
17:05:13 E ActivityThread : at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1348)
17:05:13 E ActivityThread : at android.app.ContextImpl.registerReceiver(ContextImpl.java:1328)
17:05:13 E ActivityThread : at android.app.ContextImpl.registerReceiver(ContextImpl.java:1322)
17:05:13 E ActivityThread : at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:630)
17:05:13 E ActivityThread : at guichaguri.trackplayer.metadata.components.NoisyReceiver.setEnabled(NoisyReceiver.java:38)
17:05:13 E ActivityThread : at guichaguri.trackplayer.metadata.Metadata.updatePlayback(Metadata.java:177)
17:05:13 E ActivityThread : at guichaguri.trackplayer.logic.MediaManager.onPlaybackUpdate(MediaManager.java:236)
17:05:13 E ActivityThread : at guichaguri.trackplayer.player.Playback.updateState(Playback.java:188)
17:05:13 E ActivityThread : at guichaguri.trackplayer.player.players.ExoPlayback.onPlayerStateChanged(ExoPlayback.java:201)
17:05:13 E ActivityThread : at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:364)
17:05:13 E ActivityThread : at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:99)
17:05:13 E ActivityThread : at android.os.Handler.dispatchMessage(Handler.java:102)
17:05:13 E ActivityThread : at android.os.Looper.loop(Looper.java:154)
17:05:13 E ActivityThread : at android.app.ActivityThread.main(ActivityThread.java:6823)
17:05:13 E ActivityThread : at java.lang.reflect.Method.invoke(Native Method)
17:05:13 E ActivityThread : at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
17:05:13 E ActivityThread : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)```

**Comment by dcvz** [comment]
v1.0.0 changes this functionality so this issue is currently irrelevant. closing.
