### ISSUE TITLE
NullPointerException in MediaManager.onPlay

### ISSUE THREAD

**Issue by puckey** [react-native-kit/react-native-track-player#117]
I deployed the latest version of our [Radio Garden app](https://play.google.com/store/apps/details?id=com.jonathanpuckey.radiogarden&hl=en) using `react-native-track-player` to the Google Play Store. Over 100 thousand people have installed the update. Everything seems pretty stable, so I am very happy. I plan to release a new version soon with all the refinements your library offers.

Just wanted to start off with a huge thank you to you!

I have noticed a few crashes – this one occurs in approx 2 in 1000 users:

```
java.lang.NullPointerException: 
  at guichaguri.trackplayer.logic.MediaManager.onPlay (MediaManager.java:145)
  at guichaguri.trackplayer.player.Playback.updateState (Playback.java:193)
  at guichaguri.trackplayer.player.players.ExoPlayback.onPlayerStateChanged (ExoPlayback.java:201)
  at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent (ExoPlayerImpl.java:364)
  at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage (ExoPlayerImpl.java:99)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
```

Not completely sure why / when it happens, but I think it is because `playback.getCurrentTrack()` is returning null: https://github.com/react-native-kit/react-native-track-player/blob/b6d1272118712b2d0928055d7a20dccdb20bef23/android/src/main/java/guichaguri/trackplayer/logic/MediaManager.java#L145

**Comment by puckey** [comment]
I was able to replicate this crash by switching between playing streams often..
Logcat:

```
01-15 04:54:46.399 12396 12396 D ReactNativeTrackPlayer: onStop: The service is now in background, audio focus, wake and wifi locks have been released
01-15 04:54:46.403 12396 12396 D ReactNativeTrackPlayer: onStateChange
01-15 04:54:46.405 29663 29709 V Avrcp   : Send track changed
01-15 04:54:46.405 29663 29709 D Avrcp   : sendTrackChangedRsp: Not registered or registering.
01-15 04:54:46.405 29663 29709 E Avrcp   : play status change -1➡2
01-15 04:54:46.405 29663 29709 D Avrcp   : sendPlayPosNotificationRsp: Not registered or requesting.
01-15 04:54:46.405 29663 29709 V Avrcp   : onPlaybackStateChanged: state PlaybackState {state=0, position=0, buffered position=0, speed=1.0, updated=50345922, actions=6, custom actions=[], active item id=20, error=null}
01-15 04:54:46.405 12396 12396 D ReactNativeTrackPlayer: onPlaybackUpdate
01-15 04:54:46.406 29663 29709 V Avrcp   : updatePlaybackState (1): -1➡0(PlaybackState {state=0, position=0, buffered position=0, speed=1.0, updated=50345922, actions=6, custom actions=[], active item id=20, error=null})
01-15 04:54:46.408 29663 29709 I Avrcp   : Skipping update due to invalid playback state
01-15 04:54:46.408 29663 29709 E Avrcp   : play status change -1➡0
01-15 04:54:46.408 29663 29709 D Avrcp   : sendPlayPosNotificationRsp: Not registered or requesting.
01-15 04:54:46.408 12396 12396 D ReactNativeTrackPlayer: onPlay: The service is now on foreground, audio focus, wake and wifi locks have been acquired
01-15 04:54:46.408 12396 12396 W Notification: Use of stream types is deprecated for operations other than volume control
01-15 04:54:46.409 12396 12396 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
01-15 04:54:46.410 29663 29709 V Avrcp   : updatePlaybackState (1): -1➡0(PlaybackState {state=6, position=0, buffered position=0, speed=1.0, updated=50345931, actions=6, custom actions=[], active item id=20, error=null})
01-15 04:54:46.411 29663 29709 I Avrcp   : Skipping update due to invalid playback state
01-15 04:54:46.411 29663 29709 E Avrcp   : play status change -1➡0
01-15 04:54:46.412 29663 29709 D Avrcp   : sendPlayPosNotificationRsp: Not registered or requesting.
01-15 04:54:46.412 29663 29709 V Avrcp   : onPlaybackStateChanged: state PlaybackState {state=6, position=0, buffered position=0, speed=1.0, updated=50345931, actions=6, custom actions=[], active item id=20, error=null}
01-15 04:54:46.412 29663 29709 V Avrcp   : updatePlaybackState (1): -1➡0(PlaybackState {state=6, position=0, buffered position=0, speed=1.0, updated=50345931, actions=6, custom actions=[], active item id=20, error=null})
01-15 04:54:46.413 12396 12396 D ReactNativeTrackPlayer: Requesting audio focus...
01-15 04:54:46.413 12396 12396 W AudioManager: Use of stream types is deprecated for operations other than volume control
01-15 04:54:46.413 12396 12396 W AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
01-15 04:54:46.414   894 13266 I MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10218/12396 clientId=android.media.AudioManager@18e65c2guichaguri.trackplayer.logic.components.FocusManager@2ae9fd3 req=1 flags=0x0
01-15 04:54:46.414 12396 12396 D ReactNativeTrackPlayer: Audio focus granted!
01-15 04:54:46.415 29663 29709 I Avrcp   : Skipping update due to invalid playback state
01-15 04:54:46.415 29663 29709 E Avrcp   : play status change -1➡0
01-15 04:54:46.415 29663 29709 D Avrcp   : sendPlayPosNotificationRsp: Not registered or requesting.
01-15 04:54:46.416 29663 29709 V Avrcp   : ActiveSession: MediaController (com.jonathanpuckey.radiogarden@64f4015) null, null, null
01-15 04:54:46.417 29663 29709 V Avrcp   : isBrowseSupported for com.jonathanpuckey.radiogarden: true
01-15 04:54:46.418 12396 12396 D AndroidRuntime: Shutting down VM
01-15 04:54:46.419 12396 12396 E AndroidRuntime: FATAL EXCEPTION: main
01-15 04:54:46.419 12396 12396 E AndroidRuntime: Process: com.jonathanpuckey.radiogarden, PID: 12396
01-15 04:54:46.419 12396 12396 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'boolean guichaguri.trackplayer.logic.track.Track.urlLocal' on a null object reference
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at guichaguri.trackplayer.logic.MediaManager.onPlay(MediaManager.java:150)
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at guichaguri.trackplayer.player.Playback.updateState(Playback.java:193)
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at guichaguri.trackplayer.player.players.ExoPlayback.onPlayerStateChanged(ExoPlayback.java:201)
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:364)
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:99)
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
01-15 04:54:46.419 12396 12396 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
01-15 04:54:46.421 29663 29709 D Avrcp   : update #7:MediaPlayerInfo com.jonathanpuckey.radiogarden (as 'Radio Garden') Type = 1, SubType = 0, Status = 0 Feature Bits [40 41 42 44 45 47 48 58 59 62 65 67] Controller: MediaController (com.jonathanpuckey.radiogarden@64f4015) null, null, null
```
