### ISSUE TITLE
App force close on Android 4.4.4

### ISSUE THREAD

**Issue by ariona** [react-native-kit/react-native-track-player#125]
The app force closed whenever i tried to play some audio, here is the log i get from the logcat.

Only got this error on **Android 4.4.4-API 19**, it working on Android 4.3 and 5.5 above.

```bash
E/dalvikvm( 2010): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
E/dalvikvm( 2010): Could not find class 'com.google.android.exoplayer2.source.dash.DashMediaSource', referenced from method guichaguri.trackplayer.player.players.ExoPlayback.load
E/dalvikvm( 2010): Could not find class 'com.google.android.exoplayer2.source.hls.HlsMediaSource', referenced from method guichaguri.trackplayer.player.players.ExoPlayback.load
E/dalvikvm( 2010): Could not find class 'com.google.android.exoplayer2.source.smoothstreaming.SsMediaSource', referenced from method guichaguri.trackplayer.player.players.ExoPlayback.load
E/dalvikvm( 2010): Could not find class 'com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23', referenced from method com.google.android.exoplayer2.video.MediaCodecVideoRenderer.clearRenderedFirstFrame
E/dalvikvm( 2010): Could not find class 'com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23', referenced from method com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec
E/dalvikvm( 2010): Could not find class 'android.media.AudioAttributes$Builder', referenced from method com.google.android.exoplayer2.audio.AudioTrack.createHwAvSyncAudioTrackV21
E/dalvikvm( 2010): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.facebook.react.views.view.ReactDrawableHelper.createDrawableFromJSDescription
E/AndroidRuntime( 2010): FATAL EXCEPTION: Thread-174
E/AndroidRuntime( 2010): Process: com.asaticloud, PID: 2010
E/AndroidRuntime( 2010): java.lang.NoSuchMethodError: android.media.RemoteControlClient$MetadataEditor.putObject
E/AndroidRuntime( 2010): 	at android.support.v4.media.session.MediaSessionCompatApi19.addNewMetadata(MediaSessionCompatApi19.java:80)
E/AndroidRuntime( 2010): 	at android.support.v4.media.session.MediaSessionCompatApi19.setMetadata(MediaSessionCompatApi19.java:50)
E/AndroidRuntime( 2010): 	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1729)
E/AndroidRuntime( 2010): 	at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:493)
E/AndroidRuntime( 2010): 	at guichaguri.trackplayer.metadata.Metadata.updateArtwork(Metadata.java:220)
E/AndroidRuntime( 2010): 	at guichaguri.trackplayer.metadata.components.ArtworkLoader.run(ArtworkLoader.java:62)
E/InputDispatcher(  590): channel '52b5e8e4 com.asaticloud/com.reactnativenavigation.controllers.NavigationActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
F/ActivityManager(  590): Service ServiceRecord{52cb6758 u0 com.asaticloud/guichaguri.trackplayer.logic.services.PlayerService} in process ProcessRecord{52a1c0bc 2010:com.asaticloud/u0a57} not same as in map: null
```

**Comment by Guichaguri** [comment]
It's a bug with the support lib, updating it fixes the problem.

**Comment by ariona** [comment]
Thanks for the reply, how do i update it? i am not familiar with the internal android things.

**Comment by ariona** [comment]
Should i update in on my android sdk? there is no more update to the libs. but the app still force close when trying to play the audio.

![screen shot 2018-01-29 at 10 00 34 am](https://user-images.githubusercontent.com/752483/35491651-5f48e0ea-04da-11e8-802b-7b7fca52e1c1.png)

**Comment by ariona** [comment]
After doing some searching, i have found the solution for this from react-native-music control issue, this pull request made the issue fixed, i think you should add this too?

https://github.com/tanguyantoine/react-native-music-control/pull/129/files

**Comment by mnlbox** [comment]
@ariona how you fix your problem finally?

**Comment by ariona** [comment]
By editing the file which contain this string `MediaMetadataCompat.METADATA_KEY_RATING`, and replace it with the solution from above pull request from rn music control.

I am afk, can't give you the detail.

**Comment by mnlbox** [comment]
@ariona I test it and change below line as you tell:

https://github.com/react-native-kit/react-native-track-player/blob/b096fa7bddf0b65da42c86d75016a66ad25f3d9e/android/src/main/java/guichaguri/trackplayer/metadata/Metadata.java#L119

but it's still not working.
