### ISSUE TITLE
app crash after close [Android]

### ISSUE THREAD

**Issue by cinder92** [react-native-kit/react-native-track-player#151]
Hello, when i close (kill) the app an error message appears on screen saying that unfortunately my app has crashed,

log

```
Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {13b6d7e6} sending message to a Handler on a dead thread
                                                               java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {13b6d7e6} sending message to a Handler on a dead thread
                                                                   at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                   at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                   at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                   at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                   at android.os.Handler.post(Handler.java:326)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                   at java.lang.Thread.run(Thread.java:818)
```

code

```
                
               TrackPlayer.setupPlayer({stopWithApp: true});
               TrackPlayer.add({
                    id: 'ranchPlayerAndroid',
                    url : provider.url,
                    title: 'Rancherita del Aire',
                    artist: 'Rancherita',
                    artwork // Load artwork from the app bundle
                });

                TrackPlayer.updateOptions({
                    stopWithApp: true
                });
```

**Comment by cinder92** [comment]
Any update on this?

**Comment by dcvz** [comment]
Is this still an issue with v1.0.0?

**Comment by Guichaguri** [comment]
I'll be closing this issue for inactivity. If you are still experience this problem, feel free to reopen the issue.

**Comment by raixor** [comment]
Any update on this? I have the same 
Using the branch DEV
