### ISSUE TITLE
Error: Unable to start service guichaguri.trackplayer.logic.services.PlayerTask

### ISSUE THREAD

**Issue by adidoes** [react-native-kit/react-native-track-player#201]
I've been having trouble with this error for a few days now, any idea why I get this? 
This happens only on Android.
Thanks.

```D/ReactNativeTrackPlayer: Setting up the player
I/ReactNativeTrackPlayer: Creating an ExoPlayer instance...
D/Exponent: Using cached or embedded response.
            Got cached OkHttp response for https://d1wp6m56sqw74a.cloudfront.net/%40expo-home-dev%2Fexponent-home-dev-bf2c6c97bc64f2ddfcee51d2d0cdea42ed33055a%2F25.0.0%2F0dafbec286ce3094cdfd69c3cddde606-25.0.0-android.js
            Have cached source file for https://d1wp6m56sqw74a.cloudfront.net/%40expo-home-dev%2Fexponent-home-dev-bf2c6c97bc64f2ddfcee51d2d0cdea42ed33055a%2F25.0.0%2F0dafbec286ce3094cdfd69c3cddde606-25.0.0-android.js
I/ExoPlayerImpl: Init ExoPlayerLib/2.4.3 [generic_x86, Android SDK built for x86, Google, 25]
D/ReactNative: ReactInstanceManager.ctor()
D/ReactNative: ReactInstanceManager.createReactContextInBackground()
               ReactInstanceManager.recreateReactContextInBackgroundInner()
               ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
               ReactInstanceManager.recreateReactContextInBackground()
               ReactInstanceManager.runCreateReactContextOnNewThread()
W/AsyncCondition: Could not find listener for key: experienceActivityKernelDidLoad
D/Kernel: Kernel started running.
D/ReactNative: ReactInstanceManager.createReactContext()
D/ReactNativeTrackPlayer: Updating current track...
D/ReactNativeTrackPlayer: onTrackUpdate
D/ReactNative: Initializing React Xplat Bridge.
D/ReactNativeTrackPlayer: onPlaybackUpdate
D/ReactNativeTrackPlayer: onPlay: The service is now on foreground, audio focus, wake and wifi locks have been acquired
D/ReactNative: Initializing React Xplat Bridge before initializeBridge
D/ReactNativeTrackPlayer: Requesting audio focus...
D/ReactNativeTrackPlayer: Audio focus granted!
D/ReactNativeTrackPlayer: Marking the service as started, as there is now playback
D/ReactNativeTrackPlayer: onStateChange
D/ReactNativeTrackPlayer: Sending event playback-track-changed...
D/ReactNative: Initializing React Xplat Bridge after initializeBridge
               CatalystInstanceImpl.runJSBundle()
D/ReactNative: ReactInstanceManager.setupReactContext()
               CatalystInstanceImpl.initialize()
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com, PID: 6741
                  java.lang.RuntimeException: Unable to start service guichaguri.trackplayer.logic.services.PlayerTask@5173cd5 with Intent { cmp=com/guichaguri.trackplayer.logic.services.PlayerTask (has extras) }: java.lang.ClassCastException: host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication
                      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3343)
                      at android.app.ActivityThread.-wrap21(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: java.lang.ClassCastException: host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication
                      at com.facebook.react.HeadlessJsTaskService.getReactNativeHost(HeadlessJsTaskService.java:171)
                      at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:100)
                      at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:53)
                      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3326)
                      at android.app.ActivityThread.-wrap21(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by Guichaguri** [comment]
You're probably getting this because your Application class does not implement the ReactApplication interface

**Comment by adidoes** [comment]
Thank you for your answer. I guess this is because I'm using Expo. Is there a way to get around it?

**Comment by moonstruck** [comment]
@adidoes [Ejecting from Create React Native App](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md#ejecting-from-create-react-native-app)

**Comment by adidoes** [comment]
I should have mentioned that I already ejected my app.

**Comment by efleurine** [comment]
@adidoes  did you find a solution because I am stuck now with `guichaguri.trackplayer.logic.services.PlayerService` error

it might be related?

**Comment by efleurine** [comment]
I made some changes and it seems to work
I downgraded from 
`"com.android.support:appcompat-v7:23.0.1"` (1)
to 
`"com.android.support:appcompat-v7:27.0.2"` (2)

I would have to do further testing to find the exact problem but I think some libraries needed are only in (2) and not in (1) for me. You might have the same problem.

**Comment by efleurine** [comment]
I made some changes and it seems to work
I downgraded 
from 
`"com.android.support:appcompat-v7:27.0.2"` (1)
to 

`"com.android.support:appcompat-v7:23.0.1"` (2)



I would have to do further testing to find the exact problem but I think some libraries needed are only in (2) and not in (1).

You might have the same problem.

**Comment by adidoes** [comment]
@efleurine Thanks for the info. I gave up trying to use ExpoKit because I didn't really need it. The library works without issues with ejected crna, I also think the performance of the app has improved.

**Comment by dcvz** [comment]
Looks like this issue was resolved by not using expo. I'll close this now :)
