### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method <init> in class Lcom/google/android/exoplayer2/DefaultLoadControl;

### ISSUE THREAD

**Issue by ManrickCapotolan** [react-native-kit/react-native-track-player#287]
This error appears on start:

```
ava.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/upstream/DefaultAllocator;IIJJ)V in class Lcom/google/android/exoplayer2/DefaultLoadControl; or its super classes (declaration of 'com.google.android.exoplayer2.DefaultLoadControl' appears in /data/app/com.cathedralofpraisemanila.adroitapps.android-2/base.apk:classes24.dex)
                      at guichaguri.trackplayer.player.players.ExoPlayback.<init>(ExoPlayback.java:62)
                      at guichaguri.trackplayer.logic.MediaManager.createLocalPlayback(MediaManager.java:65)
                      at guichaguri.trackplayer.logic.MediaManager.setupPlayer(MediaManager.java:78)
                      at guichaguri.trackplayer.logic.components.MediaWrapper.setupPlayer(MediaWrapper.java:36)
                      at guichaguri.trackplayer.TrackModule$1.run(TrackModule.java:143)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

package.json: 

```
"dependencies": {
    "@expo/samples": "2.1.1",
    "axios": "^0.18.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "expo": "^29.0.0",
    "expokit": "^1.5.0",
    "lodash": "^4.17.10",
    "mobx": "^4.3.1",
    "mobx-react": "^5.2.3",
    "react": "16.3.1",
    "react-mixin": "^2.0.2",
    "react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",
    "react-native-android-fullscreen-webview-video": "^1.0.3",
    "react-native-firebase": "4.0.7",
    "react-native-image-placeholder": "^1.0.14",
    "react-native-image-zoom-viewer": "^2.2.5",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-map-link": "^2.0.4",
    "react-native-onesignal": "3.2.5",
    "react-native-slider": "^0.11.0",
    "react-native-track-player": "^0.2.5",
    "react-native-wkwebview-reborn": "^1.21.0",
    "react-navigation": "2.0.0",
    "react-navigation-tabs": "^0.5.1",
    "react-timer-mixin": "^0.13.3"
  },
```

and my project dependencies:
```
compile project(':react-native-android-fullscreen-webview-video')
  compile project(':react-native-onesignal')
  compile(project(':react-native-firebase')) {
      transitive = false
  }
  compile project(':react-native-track-player')
  compile fileTree(dir: 'libs', include: ['*.jar'])

  compile 'com.android.support:multidex:1.0.3'

  // Our dependencies
  compile 'com.android.support:appcompat-v7:26.0.1'

  // Our dependencies from ExpoView
  // DON'T ADD ANYTHING HERE THAT ISN'T IN EXPOVIEW. ONLY COPY THINGS FROM EXPOVIEW TO HERE.
  compile 'com.android.support:appcompat-v7:26.0.1'
  compile 'com.facebook.android:facebook-android-sdk:4.7.0'
  compile('com.facebook.android:audience-network-sdk:4.22.1') {
    exclude module: 'play-services-ads'
  }
  provided 'org.glassfish:javax.annotation:3.1.1'
  annotationProcessor 'com.jakewharton:butterknife:7.0.1'
  compile 'com.jakewharton:butterknife:7.0.1'
  compile 'de.greenrobot:eventbus:2.4.0'
  compile 'com.amplitude:android-sdk:2.9.2' // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
  compile 'com.squareup.picasso:picasso:2.5.2'
  compile 'com.google.firebase:firebase-core:12.0.0'
  compile 'com.google.firebase:firebase-analytics:12.0.0'
  compile 'com.google.android.gms:play-services-gcm:12.0.0'
  compile 'com.google.android.gms:play-services-analytics:12.0.0'
  compile 'com.google.android.gms:play-services-maps:12.0.0'
  compile 'com.google.android.gms:play-services-auth:12.0.0'
  compile 'com.google.android.gms:play-services-location:12.0.0'
  compile 'com.google.android.gms:play-services-ads:12.0.0'
//  apt 'com.raizlabs.android:DBFlow-Compiler:2.2.1'
  compile "com.raizlabs.android:DBFlow-Core:2.2.1"
  compile "com.raizlabs.android:DBFlow:2.2.1"
  compile "com.madgag.spongycastle:core:1.53.0.0"
  compile "com.madgag.spongycastle:prov:1.53.0.0"
  debugCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta1'
  // debugCompile 'com.squareup.leakcanary:leakcanary-android:1.4-beta1'
  releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta1'
  compile 'com.facebook.device.yearclass:yearclass:1.0.1'
  compile 'commons-io:commons-io:1.3.2'
  compile 'me.leolin:ShortcutBadger:1.1.4@aar'
  compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
  compile 'com.theartofdev.edmodo:android-image-cropper:2.4.7'
  compile 'com.yqritc:android-scalablevideoview:1.0.1'
  compile 'commons-codec:commons-codec:1.10'
  compile 'com.segment.analytics.android:analytics:4.3.0'
  compile 'com.google.zxing:core:3.2.1'
  compile 'net.openid:appauth:0.4.1'
  compile 'com.airbnb.android:lottie:2.2.0'
  compile 'io.branch.sdk.android:library:2.6.1'
  compile('io.nlopez.smartlocation:library:3.2.11') {
    transitive = false
  }
  compile 'com.android.support:exifinterface:26.0.1'
  compile 'com.squareup.okhttp3:okhttp:3.4.1'
  compile 'com.squareup.okhttp3:okhttp-urlconnection:3.4.1'
  compile 'com.squareup.okhttp3:okhttp-ws:3.4.1'
  compile 'com.squareup.okio:okio:1.9.0'
```

has anyone encountered this? and has a fix?

Note that `react-native-android-fullscreen-webview-video` do not depend on exoplayer.
Thanks!

**Comment by dcvz** [comment]
seems like a problem with other dependencies. use the latest v1.0.0 release
