### ISSUE TITLE
[ANDROID][v1.0.0] module crashes when playing local files

### ISSUE THREAD

**Issue by Drazail** [react-native-kit/react-native-track-player#308]
this works perfectly fine on 0.2.5 :

`
TrackPlayer.add([{
        id: this.props.track.id,
        url: this.props.track.url, // module crashes if this points to a local file
        title: this.props.track.title,
        artist: this.props.track.performer,
        duration: this.props.track.duration,
        artwork: this.props.track.cover,
      }]).then(() => TrackPlayer.play());
`
however on 1.0.0  if the url points to a local file this exception will be thrown:

`
ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:401)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:494)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:442)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
`

**Comment by Drazail** [comment]
i got it working by using DefaultDataSource instead of DefaultHttpDataSource:


https://github.com/react-native-kit/react-native-track-player/blob/342292e4193fad4c269547ae01af04cceb5d826d/android/src/main/java/com/guichaguri/trackplayer/service/models/Track.java#L18-L19

to : 

`
import com.google.android.exoplayer2.upstream.DefaultDataSource;
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory;
`

and: 

https://github.com/react-native-kit/react-native-track-player/blob/342292e4193fad4c269547ae01af04cceb5d826d/android/src/main/java/com/guichaguri/trackplayer/service/models/Track.java#L144-L149

to : 

`
DataSource.Factory ds = new DefaultDataSourceFactory(
                ctx, userAgent
        );
`

haven't run any tests, so i don't know if this breaks other parts of the code or not.
