### ISSUE TITLE
[Android] Can't play file from network 

### ISSUE THREAD

**Issue by ishigamii** [react-native-kit/react-native-track-player#316]
Hi, after testing the iOS version I am back with some feedback on the Android version which is not working for me for the moment.

The project is linked as described in the documentation and I also added the  `Circular Reference` lines just in case (like describe here : https://github.com/react-native-kit/react-native-track-player/wiki/Installation#android-circular-referencecomandroidtoolsr8apilevelexception-default-interface-methods-are-only-supported-starting-with-android-n---min-api-24) 

**My configuration :** 

package.json
```
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-track-player": "^1.0.0",
```

Simulator Android
<img width="445" alt="capture d ecran 2018-10-25 a 11 10 20" src="https://user-images.githubusercontent.com/26909067/47489312-9857c780-d846-11e8-8b38-9a090710bf52.png">

I tried using both default configuration of the player and also this one : 
```
{
    "exoplayer": true,
    "cache": true,
    "dash": false,
    "hls": false,
    "smoothstreaming": false,
    "castApplicationId": null,
    "auto": false
  }
``` 

index.js
``` 
AppRegistry.registerComponent('xxx', () => StatusBarWarpper);
TrackPlayer.registerEventHandler(require('./player-handler.js'));
``` 

player-handler.js
```
import TrackPlayer from 'react-native-track-player';

module.exports = async (data) => {
  console.log('la', data.type, data);
  if (data.type === 'playback-state') {
    // Update the UI with the new state
  } else if (data.type === 'remote-play') {
    TrackPlayer.play();
  } else if (data.type === 'remote-pause') {
    TrackPlayer.pause();
  } else if (data.type === 'remote-seek') {
    TrackPlayer.seekTo(data.position);
  } else if (data.type === 'remote-jump-backward') {
    TrackPlayer.getPosition().then((position) => {
      TrackPlayer.seekTo(position - data.interval);
    });
  } else if (data.type === 'remote-jump-forward') {
    TrackPlayer.getPosition().then((position) => {
      TrackPlayer.seekTo(position + data.interval);
    });
  } else if (data.type === 'playback-queue-ended') {
    TrackPlayer.reset();
  }
};
```
Player stuffs
```
static async initPlayer() {
    await TrackPlayer.setupPlayer().then(() => console.log('created'));
    TrackPlayer.updateOptions({
      jumpInterval: 60,
      // The maximum height or width that the artwork can have. It will be resized when necessary. The lower the number is, the lower is the memory used
      // maxArtworkSize: 800,

      // An array of media controls capabilities
      // Can contain CAPABILITY_PLAY, CAPABILITY_PAUSE, CAPABILITY_STOP, CAPABILITY_SEEK_TO,
      // CAPABILITY_SKIP_TO_NEXT, CAPABILITY_SKIP_TO_PREVIOUS, CAPABILITY_SET_RATING
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SEEK_TO,
        TrackPlayer.CAPABILITY_JUMP_FORWARD,
        TrackPlayer.CAPABILITY_JUMP_BACKWARD,
      ],

      // Notification Color (Must be an ARGB Hexadecimal number)
      color: 'red',
    });
  }

  static addTrack(path: string) {
    if (path && path.length >= 0) {
      const track = {
        id: 'u234325245lezkj',

        url: path, // Load media from the network
        // url: require('./avaritia.mp4'), // Load media from the app bundle

        title: 'Avaritia',
        artist: 'deadmau5',
        album: 'while(1<2)',
        genre: 'Progressive House, Electro House',
        date: '2014-05-20T07:00:00+00:00', // RFC 3339

        artwork: 'https://www.luxuryhomestore.co.uk/ekmps/shops/1aec64/images/patrice-murciano-liquid-resin-paint-large-artwork-monkey-dj-2133-p.jpeg', // Load artwork from the network
        // artwork: require('./avaritia.jpg'), // Load artwork from the app bundle
      };
      return TrackPlayer.add(track);
    }
    return null;
  }

  static async playPause() {
    // State is one of STATE_NONE, STATE_PLAYING, STATE_PAUSED, STATE_STOPPED, STATE_BUFFERING
    const state = await TrackPlayer.getState();
    if (state === TrackPlayer.STATE_PLAYING) {
      TrackPlayer.pause();
    } else if (state === TrackPlayer.STATE_PAUSED
      || state === TrackPlayer.STATE_STOPPED) {
      TrackPlayer.play();
    }
  }
```
**Problems**
As soon as I start the app and create the player, I start getting event loop from the player into the player-handler.js. 

```
la undefined {} <==== PLAYER NOT CREATED
blob:http://localhos…7817a5138489:126212 created <==== PLAYER CREATED
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 1}
blob:http://localhos…7817a5138489:181812 la playback-queue-ended {type: "playback-queue-ended", position: 0, track: null}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 0}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 1}
blob:http://localhos…7817a5138489:181812 la playback-queue-ended {type: "playback-queue-ended", position: 0, track: null}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 0}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 1}
blob:http://localhos…7817a5138489:181812 la playback-queue-ended {type: "playback-queue-ended", position: 0, track: null}
...
```

And after adding my track (that is working on iOS) I get another loop : 

```
added <=== TRACK ADDDED
la playback-track-changed {type: "playback-track-changed", nextTrack: "u234325245lezkj", position: -0.001, track: null} <=== TRACK IN THE QUEUE
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 1}
blob:http://localhos…7817a5138489:181812 la playback-queue-ended {type: "playback-queue-ended", position: 0, track: null}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 0}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 1}
blob:http://localhos…7817a5138489:181812 la playback-queue-ended {type: "playback-queue-ended", position: 0, track: null}
blob:http://localhos…7817a5138489:181812 la playback-queue-ended {type: "playback-queue-ended", position: 0, track: null}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 0}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 6}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 1}
blob:http://localhos…7817a5138489:181812 la playback-queue-ended {type: "playback-queue-ended", position: 0, track: null}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 0}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 6}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 1}
blob:http://localhos…7817a5138489:181812 la playback-queue-ended {type: "playback-queue-ended", position: 0, track: null}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 0}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 6}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 0}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 6}
blob:http://localhos…7817a5138489:181812 la playback-state {type: "playback-state", state: 1}
...
```

For some reason the track seems to be skipped or having trouble being played. 

When I close the app I also get a crash : 
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
       at com.guichaguri.trackplayer.service.MusicService.onStartCommand(MusicService.java:53)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3326)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Detail or not, when I am putting the app in background I can see the play icon on the top left of the phone blinking.

Thanks a lot for any help 👍

**Comment by visagegod** [comment]
1.0.0 has caused the same issue for me.

**Comment by ishigamii** [comment]
@Guichaguri sorry for the delay, I just tried the dev branch and I am experimenting the same problems. 

As soon as I create the player, I get lots of events and after adding the track to the player another loop starting as describe in my first post. Only change is that now when I close the app I don't get a crash. (the NPE I was describing at the end of my first post)

It seems to me that either the track is never added or the track is considered as played directly so jumping to the next in queue. The iOS Version with the same code is working very fine.

package.json : 
```
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-track-player": "react-native-kit/react-native-track-player#dev",
```

**Comment by Guichaguri** [comment]
Can you send the track (URL or file) that is not working so we can try to reproduce the problem?

**Comment by ishigamii** [comment]
@Guichaguri I think my problem is a configuration problem more than anything else. Though your message made me try few more things for Android. 

The file I used for my tests is a **mp3** you can find it here : 

http://otrrlibrary.org/OTRRLib/Library%20Files/A%20Series/Agatha%20Christie%201/Poirots%20Christmas/AgathaChristie___PoirotsChristmas_Pt1.mp3

I tried to stream it from the url but also to include it in my project and I get the same result for both methods. As soon as I create the player it starts receiving infinite events (which seems very strange to me considering nothing is happening and that in iOS we don't have this) and then adding the songs goes to the `then` and not the `catch` so it seems to be successful. 

Let me know if you need any other informations about the code I am using that I didn't already included.  

In my `playerView` I am initializing the player in the `constructor` method  calling the static method

```
Player.initPlayer();
```

 and then adding the track and playing when added : 
```
        Player.addTrack(path).then(() => {
          console.log('added');
          this.updateState({ isPlaying: true, isReady: true });
          Player.playPauseTrack();
        }).catch(err => console.log('err adding Track', err));
``` 

Thanks for the help 👍

**Comment by Guichaguri** [comment]
Does it still happens in 1.0.2?

**Comment by Guichaguri** [comment]
The URL seems to work fine for me. I'll be closing the issue for inactivity.

**Comment by ishigamii** [comment]
Sorry I didn't have time to test it yet I will try it shortly

**Comment by ishigamii** [comment]
@Guichaguri I am glad to say that the new version 
```
    "react-native-track-player": "^1.1.2",
```
Is working pretty nicely on Android
