### ISSUE TITLE
[ANDROID] app crashes after dismissing the notification

### ISSUE THREAD

**Issue by Drazail** [react-native-kit/react-native-track-player#317]
when the notifications are dismissed, the app crashes.

here are the logs:

```JAVA
2018-10-26 00:13:13.675 25053-25053/com.**** D/RNTrackPlayer: onPause
2018-10-26 00:13:13.677 25053-25053/com.**** D/RNTrackPlayer: Abandoning audio focus...
2018-10-26 00:13:13.683 25053-25053/com.**** D/RNTrackPlayer: onStateChange
2018-10-26 00:13:13.698 25053-25053/com.**** D/Notification: allPendingIntents
2018-10-26 00:13:19.322 25053-25053/com.**** D/RNTrackPlayer: Releasing service resources...
2018-10-26 00:13:19.323 25053-25053/com.**** I/ExoPlayerImpl: Release c444c96 [ExoPlayerLib/2.9.0] [herolte, SM-G930F, samsung, 26] [goog.exo.core]
2018-10-26 00:13:19.332 25053-25179/com.**** D/AudioTrack: stop() called with 0 frames delivered
2018-10-26 00:13:19.335 25053-25149/com.**** I/ACodec: [OMX.SEC.mp3.dec] Now Executing->Idle
2018-10-26 00:13:19.355 25053-25149/com.**** I/ACodec: [OMX.SEC.mp3.dec] Now Idle->Loaded
2018-10-26 00:13:19.355 25053-25149/com.**** I/ACodec: [OMX.SEC.mp3.dec] Now Loaded
2018-10-26 00:13:19.355 25053-25149/com.**** I/ACodec:  [OMX.SEC.mp3.dec] Now kWhatShutdownCompleted event : 8483
2018-10-26 00:13:19.361 25053-25149/com.**** I/ACodec:  [OMX.SEC.mp3.dec] Now uninitialized
2018-10-26 00:13:19.361 25053-25149/com.**** I/ACodec:  [] Now kWhatShutdownCompleted event : 8483
2018-10-26 00:13:19.361 25053-25149/com.**** I/MediaCodec: Codec shutdown complete
2018-10-26 00:13:19.452 25053-25059/com.**** I/zygote: Thread[3,tid=25059,WaitingInMainSignalCatcherLoop,Thread*=0xeaef4c00,peer=0x12d40698,"Signal Catcher"]: reacting to signal 3
2018-10-26 00:13:19.640 25053-25059/com.**** I/zygote: Wrote stack traces to '/data/anr/traces.txt'
2018-10-26 00:13:20.120 25053-25053/com.**** I/ExoPlayerImpl: Init d308af2 [ExoPlayerLib/2.9.0] [herolte, SM-G930F, samsung, 26]
2018-10-26 00:13:20.132 25053-25053/com.**** D/RNTrackPlayer: onStateChange
2018-10-26 00:13:20.144 25053-25053/com.**** D/RNTrackPlayer: onEnd
2018-10-26 00:13:20.616 25053-25053/com.**** D/ViewRootImpl@ae9761c[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1
2018-10-26 00:13:25.574 25053-25053/com.**** D/AndroidRuntime: Shutting down VM
2018-10-26 00:13:25.577 25053-25053/com.**** E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.**** , PID: 25053
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
```

**Comment by hqdai** [comment]
hi @dcvz, @Guichaguri,
I think this relates to the issue that I mentioned before, when user trying to destroy player for the second time (first time is ok), the unbindService() (line 157) in MusicModule.java will make the app crash. David has added condition for checking it based on context  (if context != null) but I think it's not enough.

**Comment by Guichaguri** [comment]
@hqdai I don't think it's related, but here is a potential fix: 871e5cfcf8b350282a0fd964b576f9f1cf4c5d6c. Can you try it out?

**Comment by Drazail** [comment]
@hqdai, i don't think its related to that issue, in the case of android O [after startForegroundService() the app has 5 seconds to call startForeground()](https://developer.android.com/about/versions/oreo/background), here it fails to do so hence the crash.


> 2018-10-26 00:13:**20**.616 25053-25053/com.**** D/ViewRootImpl@ae9761c[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1
> 2018-10-26 00:13:**25**.574 25053-25053/com.**** D/AndroidRuntime: Shutting down VM

**Comment by jankrah12** [comment]
@Guichaguri any resolution on this? I have the latest commit with the 'potential fix' and I'm still experiencing the issue.

**Comment by Guichaguri** [comment]
@jankrah12 can you try the latest version?
