### ISSUE TITLE
[Android] Can't play local audio

### ISSUE THREAD

**Issue by cinder92** [react-native-kit/react-native-track-player#349]
Hello, i have a native module that retrives songs from sdcard, in this case, it returns a string of absolute path

Ex 
`file:///sdcard/emulated/0/mysong.mp3`

passing this string to `url` of track player result in a error

```
java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:494)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:442)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

i tried to with `asset:///sdcard/emulated/0/mysong.mp3`, but its not working.

any advice?

**Comment by Guichaguri** [comment]
Which version are you using? Are you using the `dev` branch?

**Comment by cinder92** [comment]
@Guichaguri  sorry was my bad, but i have another issue, im going to open another issue

**Comment by brenwell** [comment]
I am having the same problem, I tried to use the dev branch but nothing was forking for me there so I had to revert 1.0.0. Is it possible to share simply what was changed here so I can edit my fork. Thanks for all the hard work @Guichaguri

**Comment by brenwell** [comment]
Great thanks!
