### ISSUE TITLE
[Android] Can't play flac audio 

### ISSUE THREAD

**Issue by cinder92** [react-native-kit/react-native-track-player#350]
after implement correctly your plugin, im tried to play .flac files, after that i gor rhis eror in AS

```
11-22 19:36:48.001 32513-608/com.fancyplayer E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
11-22 19:36:48.003 32513-32513/com.fancyplayer E/RNTrackPlayer: Playback error: exoplayer - None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
11-22 19:37:03.407 32513-32513/com.fancyplayer E/NotificationManager: notifyAsUser: tag=null, id=1, user=UserHandle{0}
```

any advice?

**Comment by Guichaguri** [comment]
As specified in the [supported format list](https://google.github.io/ExoPlayer/supported-formats.html), you have to install the [Flac extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac) in order to play .flac files. Unfortunately, there are no maven artifacts for this extension, it needs to be built manually, which you can find instructions [here](https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac#build-instructions).

Alternatively, you can use the [FFmpeg extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg), which supports a ton of formats, but it needs to be built manually as well.

**Comment by deepaksingh16** [comment]
@cinder92 Were you able to add support for other extensions?
