### ISSUE TITLE
Error running `react-native run-ios`

### ISSUE THREAD

**Issue by saintograph** [react-native-kit/react-native-track-player#392]
System specs:

- Xcode 10
- iPhone X simulator
- React-Native `0.57.8`

The following steps:

1. `yarn add react-native-track-player`
2. `react-native link`
3. `react-native run-ios`

Results in the following error:

```
Traceback (most recent call last):
        11: from /Users/saintograph/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
        10: from /Users/saintograph/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
         9: from /Users/saintograph/.rvm/gems/ruby-2.5.3/bin/xcpretty:23:in `<main>'
         8: from /Users/saintograph/.rvm/gems/ruby-2.5.3/bin/xcpretty:23:in `load'
         7: from /Users/saintograph/.rvm/gems/ruby-2.5.3/gems/xcpretty-0.3.0/bin/xcpretty:83:in `<top (required)>'
         6: from /Users/saintograph/.rvm/gems/ruby-2.5.3/gems/xcpretty-0.3.0/bin/xcpretty:83:in `each_line'
         5: from /Users/saintograph/.rvm/gems/ruby-2.5.3/gems/xcpretty-0.3.0/bin/xcpretty:84:in `block in <top (required)>'
         4: from /Users/saintograph/.rvm/gems/ruby-2.5.3/gems/xcpretty-0.3.0/lib/xcpretty/printer.rb:19:in `pretty_print'
         3: from /Users/saintograph/.rvm/gems/ruby-2.5.3/gems/xcpretty-0.3.0/lib/xcpretty/formatters/formatter.rb:88:in `pretty_format'
         2: from /Users/saintograph/.rvm/gems/ruby-2.5.3/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:307:in `parse'
         1: from /Users/saintograph/.rvm/gems/ruby-2.5.3/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:434:in `update_test_state'
/Users/saintograph/.rvm/gems/ruby-2.5.3/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:434:in `===': invalid byte sequence in US-ASCII (ArgumentError)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at Socket.<anonymous> (/Users/saintograph/projects/shinefm-mobile-app/node_modules/react-native/local-cli/runIOS/runIOS.js:309:24)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at doWrite (_stream_writable.js:411:11)
    at writeOrBuffer (_stream_writable.js:399:5)
    [... lines matching original stack trace ...]
    at readableAddChunk (_stream_readable.js:268:11)
```

**Comment by saintograph** [comment]
Oddly, the setup works today after an OS reboot. Closing this as resolved.
