### ISSUE TITLE
[Android] FATAL EXCEPTION: java.lang.NullPointerException

### ISSUE THREAD

**Issue by retyui** [react-native-kit/react-native-track-player#394]
## Description
This error always crashed application when you call `.skip(null)`:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.kykysiki.boom, PID: 26622
                  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                      at com.guichaguri.trackplayer.service.player.ExoPlayback.skip(ExoPlayback.java:69)
                      at com.guichaguri.trackplayer.module.MusicModule.lambda$skip$5(MusicModule.java:254)
                      at com.guichaguri.trackplayer.module.-$$Lambda$MusicModule$3kZ19SvqlW9XI49aL-HVhhPjHgY.run(Unknown Source:6)
                      at android.os.Handler.handleCallback(Handler.java:873)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:214)
                      at android.app.ActivityThread.main(ActivityThread.java:6981)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by retyui** [comment]
Can you add validation for `track id`?
