### ISSUE TITLE
Running code while streaming in background

### ISSUE THREAD

**Issue by helloagain-dev** [react-native-kit/react-native-track-player#419]
I want to stream an icecast radio stream which works fine.
However, I also want to update the title/artist and cover regularly.
I can fetch this data from a REST API.

How can I run code that fetches this data every 10 seconds (or so) and updates the Player regularly?
Can I put a long-running task that does the fetch into ``TrackPlayer.registerPlaybackService``?

**Comment by curiousdustin** [comment]
Maybe not exactly what you want, but I'm using this to periodically check the state and progress of the player.

https://github.com/ocetnik/react-native-background-timer

**Comment by helloagain-dev** [comment]
That seems to be exactly what I want.
I can start this when I the user hits play and it will continue running every few seconds as long as the stream is active? In the callback I can access ``TrackPlayer``?
Do you have some sample code where you run this together with ``react-native-track-player``?
All the other solutions I found, only run once every 15 minutes or so and are used to do background downloads.

**Comment by curiousdustin** [comment]
NOTE: On android if you try to access the player after it has been destroyed, this causes some errors. I haven't worked out all the kinks on my implementation yet, but in general this has been working for me so far.

```
async function setupPlayer() {
  await TrackPlayer.setupPlayer();

  let playerOptions = { ...options, ...trackPlayerOptions };
  await TrackPlayer.updateOptions(playerOptions);

  startMonitoring();
}

const MONITOR_INTERVAL = 5000;

function startMonitoring() {
  BackgroundTimer.runBackgroundTimer(() => {
    monitorProgress();
  }, MONITOR_INTERVAL);
}

async function monitorProgress() {
  try {
    let playerState = await TrackPlayer.getState();
... do stuff ...
  } catch (error) {
    console.log(error);
  }
}
```

**Comment by curiousdustin** [comment]
I am still struggling with this actually. If the app is backgrounded for a bit. Android decides to kill the player because it is idle. At this point any code that attempts to run `TrackPlayer` methods will cause the app to crash with the following error. This includes the `setupPlayer()` method.

```2019-01-30 11:56:25.613 19846-19884/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: fm.pinna.app, PID: 19846
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=fm.pinna.app/com.guichaguri.trackplayer.service.MusicService }: app is in background uid UidRecord{80589ef u0a341 SVC  bg:+1m0s18ms idle procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1506)
        at android.app.ContextImpl.startService(ContextImpl.java:1462)
        at android.content.ContextWrapper.startService(ContextWrapper.java:644)
        at android.content.ContextWrapper.startService(ContextWrapper.java:644)
        at com.guichaguri.trackplayer.module.MusicModule.waitForConnection(MusicModule.java:100)
        at com.guichaguri.trackplayer.module.MusicModule.setupPlayer(MusicModule.java:150)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by curiousdustin** [comment]
I should clarify, this is if the player has been setup, but not played anything yet, then the app is backgrounded.

**Comment by curiousdustin** [comment]
I will try getting around this by only running my background code while the player is in its playing state.

**Comment by curiousdustin** [comment]
In my case, I determined that I only need to run my background timer while the player is in the playing state. So I start and stop that timer/interval as needed. For now this seems to have avoided all the crashing cases I was running into.


However, now you made me curious.

When you say the "playback service" is the perfect place to add more code, are you saying there is a way to put more functionality into the background task by adding something to the code below? 

Is there a way I could create a timer as part of this?

```
TrackPlayer.registerPlaybackService(() =>
    require('./track-player/TrackPlayerPlaybackService.js')
  );
```

Right now my `TrackPlayerPlaybackService.js` file just contains a bunch of calls to `TrackPlayer.addEventListener()` for all the events. Could I somehow start and stop a timer in there as well? How do you tell when the service is destroyed?

**Comment by Guichaguri** [comment]
You're right, you can run any type of code there. One interesting use-case is for recording analytics data.

There is no event for destroying the service as of yet. Although in you can achieve your goal by registering an interval in `playback-track-changed` and then unregistering it in `playback-queue-ended`.

```js
let interval = null;

TrackPlayer.addEventListener('playback-track-changed', () => {
    if (interval == null) interval = setInterval(...);
});

TrackPlayer.addEventListener('playback-queue-ended', () => {
    if (interval != null) {
        clearInterval(interval);
        interval = null;
    }
});
```

I haven't tested something like this, but it should work.

**Comment by Guichaguri** [comment]
React Native shares the same Javascript context for both the service and the app itself. When the app is closed and the service is destroyed, it should also destroy the context, stopping the timer.

**Comment by curiousdustin** [comment]
Perfect, I will give this a shot and see if I can do it this way instead of using a separate library.

**Comment by helloagain-dev** [comment]
I did try @Guichaguri's proposal, but the `setInterval` function is not called anymore as soon as I put the App to the background (via Home button).

**Comment by helloagain-dev** [comment]
`react-native-background-timer` seems to work great.
But I now struggle with updating the Metadata of the notification without stopping the player and queuing the same stream again which would lead to a small pause. Is there any way with the current API to update the artist, title and artwork while the song is playing?

**Comment by moonstruck** [comment]
@helloagain-dev Possibly updating metadata on the fly is not available yet. There's two open pull request in this regard. https://github.com/react-native-kit/react-native-track-player/pull/384 and https://github.com/react-native-kit/react-native-track-player/pull/384

**Comment by ishigamii** [comment]
Hi, I am having the same crash on Android very occasionnaly : 
```
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.xxx/com.guichaguri.trackplayer.service.MusicService }: app is in background uid UidRecord{39a05c9 u0a454 CEM  bg:+1m5s685ms idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at com.guichaguri.trackplayer.module.MusicModule.waitForConnection(MusicModule.java:100)
       at com.guichaguri.trackplayer.module.MusicModule.getPosition(MusicModule.java:405)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by xgustavoh** [comment]
@helloagain-dev, Look #552

**Comment by curiousdustin** [comment]
Closing this as the original question has been answered. 

Also metadata update is part of v2.
See https://github.com/react-native-kit/react-native-track-player/pull/634
