### ISSUE TITLE
How to mock for tests?

### ISSUE THREAD

**Issue by whoislewys** [react-native-kit/react-native-track-player#501]
There should be an example in the `/example` dir of how to mock the TrackPlayer for tests

I keep getting the error
```
Invariant Violation: Native module cannot be null.
      at invariant (node_modules/react-native/node_modules/fbjs/lib/invariant.js:40:15)
      at new invariant (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:36:7)
      at Object.<anonymous> (node_modules/react-native-track-player/lib/index.js:5:45)
      at Object.<anonymous> (node_modules/react-native-track-player/index.js:4:1)
```
when trying to run a basic test

How do I mock the TrackPlayer for tests?

Thanks

**Comment by whoislewys** [comment]
There might be a better way to do this as I'm new to Jest but this worked for me stub to get basic render tests passing

I have in myproj/jest/setup.js
```
jest.mock('react-native-track-player', () => {
  return {
    addEventListener: jest.fn(),
    registerEventHandler: jest.fn(),
    registerPlaybackService: jest.fn(),
    setupPlayer: jest.fn(),
    destroy: jest.fn(),
    updateOptions: jest.fn(),
    add: jest.fn(),
    remove: jest.fn(),
    skip: jest.fn(),
    skipToNext: jest.fn(),
    skipToPrevious: jest.fn(),
    removeUpcomingTracks: jest.fn(),
    // playback commands
    reset: jest.fn(),
    play: jest.fn(),
    pause: jest.fn(),
    stop: jest.fn(),
    seekTo: jest.fn(),
    setVolume: jest.fn(),
    setRate: jest.fn(),
    // player getters
    getQueue: jest.fn(),
    getTrack: jest.fn(),
    getCurrentTrack: jest.fn(),
    getVolume: jest.fn(),
    getDuration: jest.fn(),
    getPosition: jest.fn(),
    getBufferedPosition: jest.fn(),
    getState: jest.fn(),
    getRate: jest.fn(),
  };
});
```

and in myproj/package.json
```
  "jest": {
    "preset": "react-native",
    "setupFilesAfterEnv":  ["./jest/setup.js"]
  },
```

I think it would be hugely helpful to have an example of mocking the TrackPlayer in the `/example` directory of this project, and I'd be glad to open a PR for this if the maintainers like

**Comment by rochapablo** [comment]
Nice! And did you also have to manage this?

```
Test suite failed to run

    TypeError: Class extends value undefined is not a constructor or null

       6 | import Ctrl, { IProps, IState } from '../../controllers/player';
       7 |
    >  8 | class Player extends ProgressComponent<IProps, IState> {
         |                      ^
       9 |   public async componentDidMount() {
      10 |     await this.props.init();
      11 |   }
```

**Comment by jvandenaardweg** [comment]
> Oops, just add `ProgressComponent: jest.fn(),` did work.

When I do it like that, i get an error:
`TypeError: Class constructor AudioPlayerProgressBar cannot be invoked without 'new'`

```
jest.mock('react-native-track-player', () => {
  return {
    [...]
    ProgressComponent: jest.fn()
  };
});
```
Am I missing something?

**Comment by rochapablo** [comment]
Not sure, but see if this any of this can help

```
"jest": {
    "preset": "react-native",
    "setupFiles": [
      "<rootDir>/__tests__/setup.js"
    ],
    "globals": {
      "window": {}
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json"
    ],
    "modulePaths": [
      "<rootDir>"
    ],
    "testRegex": "/__tests__/.*.test.(js|tsx|ts)?$",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor",
      "^.+\\.(js|jsx)?$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.(ts|tsx)?$": "<rootDir>/node_modules/ts-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|react-navigation|@react-navigation/.*))"
    ]
  },
```

Plus, check if you don't have multiple jest config, for example; inside `package.json` and `jest.config.js`. I had and that took me some time to figure it out.

**Comment by jakecronin** [comment]
I struggled with this challenge earlier today. My solution: 

jest-setup.js
```
import React from 'react'

class MockComponent extends React.Component {
  render() {
    return <>{this.props.children}</>
  }
}
{... other mocks}

jest.mock('react-native-track-player', () => {
  return {
    {... other mocks}
    ProgressComponent: () => MockComponent,
  }
})
```

Gladly welcome any improvements.

**Comment by LorandP** [comment]
The problem I have is that if I add the mock to `jest.setup.js` then the mocks I do in my tests do not get applied so then I do not have full control over the tests. I don't think this solves it entirely.

**Comment by jtstodola** [comment]
```jest.mock('react-native-track-player', () => ({
  __esModule: true,
  default: {
    addEventListener: () => ({
      remove: jest.fn()
    }),
    registerEventHandler: jest.fn(),
    registerPlaybackService: jest.fn(),
    setupPlayer: jest.fn(),
    destroy: jest.fn(),
    updateOptions: jest.fn(),
    reset: jest.fn(),
    add: jest.fn(),
    remove: jest.fn(),
    skip: jest.fn(),
    skipToNext: jest.fn(),
    skipToPrevious: jest.fn(),
    removeUpcomingTracks: jest.fn(),
    // playback commands
    play: jest.fn(),
    pause: jest.fn(),
    stop: jest.fn(),
    seekTo: jest.fn(),
    setVolume: jest.fn(),
    setRate: jest.fn(),
    // player getters
    getQueue: jest.fn(),
    getTrack: jest.fn(),
    getCurrentTrack: jest.fn(),
    getVolume: jest.fn(),
    getDuration: jest.fn(),
    getPosition: jest.fn(),
    getBufferedPosition: jest.fn(),
    getState: jest.fn(),
    getRate: jest.fn()
  },
  useTrackPlayerProgress: () => ({
    position: 100,
    duration: 200
  })
}));```

**Comment by IsmailJanParacha** [comment]
TypeError: Cannot read properties of undefined (reading 'ContinuePlayback')

      192 |       await TrackPlayer.updateOptions({
      193 |         android: {
    > 194 |           appKilledPlaybackBehavior: AppKilledPlaybackBehavior.ContinuePlayback,
i mock the update option but still im getting this error

**Comment by nived-cv** [comment]
hey, If anyone gets error on using `useProgress` 

```
jest.mock('react-native-track-player', () => ({
  __esModule: true,
  default: {
    addEventListener: () => ({
      remove: jest.fn()
    }),
    registerEventHandler: jest.fn(),
    registerPlaybackService: jest.fn(),
    setupPlayer: jest.fn(),
    destroy: jest.fn(),
    updateOptions: jest.fn(),
    reset: jest.fn(),
    add: jest.fn(),
    remove: jest.fn(),
    skip: jest.fn(),
    skipToNext: jest.fn(),
    skipToPrevious: jest.fn(),
    removeUpcomingTracks: jest.fn(),
    // playback commands
    play: jest.fn(),
    pause: jest.fn(),
    stop: jest.fn(),
    seekTo: jest.fn(),
    setVolume: jest.fn(),
    setRate: jest.fn(),
    // player getters
    getQueue: jest.fn(),
    getTrack: jest.fn(),
    getCurrentTrack: jest.fn(),
    getVolume: jest.fn(),
    getDuration: jest.fn(),
    getPosition: jest.fn(),
    getBufferedPosition: jest.fn(),
    getState: jest.fn(),
    getRate: jest.fn(),
  },
  // hooks
  useProgress: () => ({
    position: 0,
    duration: 0
  })
}));
```

**Comment by MoritzCooks** [comment]
@IsmailJanParacha did you find a solution for your issue? 
I'm facing a similar issue but with IOSCategory.Playback:

```
    TypeError: Cannot read properties of undefined (reading 'Playback')

      38 |   playBuffer: 5,
      39 |   backBuffer: 30,
    > 40 |   iosCategory: IOSCategory.Playback,
         |                            ^
      41 |   iosCategoryMode: IOSCategoryMode.Default,
```

I was able to mock most of the constants too by adding them, but IOSCategory seems to need a bit more attention:

```TS
jest.mock('react-native-track-player', () => {
  return {
    __esModule: true,
    default: {
      addEventListener: () => ({
        remove: jest.fn(),
      }),
      registerEventHandler: jest.fn(),
      registerPlaybackService: jest.fn(),
      setupPlayer: jest.fn(),
      destroy: jest.fn(),
      updateOptions: jest.fn(),
      reset: jest.fn(),
      add: jest.fn(),
      remove: jest.fn(),
      skip: jest.fn(),
      skipToNext: jest.fn(),
      skipToPrevious: jest.fn(),
      removeUpcomingTracks: jest.fn(),
      // playback commands
      play: jest.fn(),
      pause: jest.fn(),
      stop: jest.fn(),
      seekTo: jest.fn(),
      setVolume: jest.fn(),
      setRate: jest.fn(),
      // player getters
      getQueue: jest.fn(),
      getTrack: jest.fn(),
      getCurrentTrack: jest.fn(),
      getVolume: jest.fn(),
      getDuration: jest.fn(),
      getPosition: jest.fn(),
      getBufferedPosition: jest.fn(),
      getState: jest.fn(),
      getRate: jest.fn(),
      // constants
      constants: {
        CAPABILITY_PLAY: 1,
        CAPABILITY_PLAY_FROM_ID: 2,
        CAPABILITY_PLAY_FROM_SEARCH: 4,
        CAPABILITY_PAUSE: 8,
        CAPABILITY_STOP: 16,
        CAPABILITY_SEEK_TO: 32,
        CAPABILITY_SKIP: 64,
        CAPABILITY_SKIP_TO_NEXT: 128,
        CAPABILITY_SKIP_TO_PREVIOUS: 256,
        CAPABILITY_JUMP_FORWARD: 512,
        CAPABILITY_JUMP_BACKWARD: 1024,
        CAPABILITY_SET_RATING: 2048,
        CAPABILITY_LIKE: 4096,
        CAPABILITY_DISLIKE: 8192,
        CAPABILITY_BOOKMARK: 16384,
        CAPABILITY_SKIP_TO_QUEUE_ITEM: 32768,
        CAPABILITY_PLAY_FROM_MEDIA_ID: 65536,
        CAPABILITY_PLAY_FROM_SEARCH_WITH_EXTRAS: 131072,
        CAPABILITY_PAUSE_RESUME: 262144,
        CAPABILITY_PLAY_FROM_URI: 524288,
        CAPABILITY_PLAY_FROM_SEARCH_AND_PLAY: 1048576,
        CAPABILITY_SET_RATING_INDICATOR: 2097152,
        CAPABILITY_SET_REPEAT_MODE: 4194304,
        CAPABILITY_SET_SHUFFLE_MODE: 8388608,
        CAPABILITY_SET_SPEED: 16777216,
        CAPABILITY_SET_QUEUE: 33554432,
        CAPABILITY_SET_QUEUE_TITLE: 67108864,
        CAPABILITY_SET_QUEUE_ITEM_TITLE: 134217728,
        CAPABILITY_SET_MEDIA_ITEM_METADATA: 268435456,
        CAPABILITY_SET_MEDIA_ITEM_IMAGE: 536870912,
        CAPABILITY_SET_MEDIA_ITEM_URI: 1073741824,
        CAPABILITY_SET_MEDIA_ITEM_REPEAT_MODE: 2147483648,
        CAPABILITY_SET_MEDIA_ITEM_SHUFFLE_MODE: 4294967296,
        CAPABILITY_SET_MEDIA_ITEM_SPEED: 8589934592,
        CAPABILITY_SET_MEDIA_ITEM_QUEUE: 17179869184,
        CAPABILITY_SET_MEDIA_ITEM_QUEUE_TITLE: 34359738368,
        CAPABILITY_SET_MEDIA_ITEM_QUEUE_ITEM_TITLE: 68719476736,
        CAPABILITY_SET_MEDIA_ITEM_MEDIA_ITEM_METADATA: 137438953472,
        CAPABILITY_SET_MEDIA_ITEM_MEDIA_ITEM_IMAGE: 274877906944,
        CAPABILITY_SET_MEDIA_ITEM_MEDIA_ITEM_URI: 549755813888,
        CAPABILITY_SET_MEDIA_ITEM_MEDIA_ITEM_REPEAT_MODE: 109,
        IOSCategoryOptions: {
          MixWithOthers: 'mixWithOthers',
          DuckOthers: 'duckOthers',
          InterruptSpokenAudioAndMixWithOthers:
            'interruptSpokenAudioAndMixWithOthers',
          AllowBluetooth: 'allowBluetooth',
          AllowBluetoothA2DP: 'allowBluetoothA2DP',
          AllowAirPlay: 'allowAirPlay',
          DefaultToSpeaker: 'defaultToSpeaker',
        },
        IOSCategoryMode: {
          Default: 'default',
          GameChat: 'gameChat',
          Measurement: 'measurement',
          MoviePlayback: 'moviePlayback',
          SpokenAudio: 'spokenAudio',
          VideoChat: 'videoChat',
          VideoRecording: 'videoRecording',
          VoiceChat: 'voiceChat',
          VoicePrompt: 'voicePrompt',
        },
        IOSCategory: {
          Playback: 'playback',
          PlaybackAndRecord: 'playbackAndRecord',
          MultiRoute: 'multiRoute',
          Ambient: 'ambient',
          SoloAmbient: 'soloAmbient',
          Record: 'record',
          PlayAndRecord: 'playAndRecord',
        },
      },
    },
    useTrackPlayerProgress: () => ({
      position: 100,
      duration: 200,
    }),
  }
})

```
