### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference

### ISSUE THREAD

**Issue by eff-society** [react-native-kit/react-native-track-player#514]
My app was working fine but suddenly started crashing without any error. I've tried rebuilding and reinstalling the app several times but no use.
adb logcat shows the following error when app crashes.

```
03-27 01:20:00.457 12477 12477 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.guichaguri.trackplayer.service.models.Track.toMediaMetadata(Track.java:116)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.guichaguri.trackplayer.service.metadata.MetadataManager.updateMetadata(MetadataManager.java:194)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.guichaguri.trackplayer.service.MusicManager.onTrackUpdate(MusicManager.java:193)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.guichaguri.trackplayer.service.player.ExoPlayback.onPositionDiscontinuity(ExoPlayback.java:220)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.guichaguri.trackplayer.service.player.ExoPlayback.onTimelineChanged(ExoPlayback.java:200)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners(ExoPlayerImpl.java:771)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:708)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:639)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:584)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:125)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:238)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6006)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:937)
03-27 01:20:00.457 12477 12477 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:798)
03-27 01:20:00.476 12477 12597 E LoadTask: Unexpected exception loading stream
```

**Comment by Guichaguri** [comment]
That can happen when you feed the player empty or invalid track URLs. Can you share the code that adds the track into the queue?

**Comment by eff-society** [comment]
Thank you for your quick response. I traced the error causing code to this snippet. App doesn't crash when I comment it out. Tho still can't figure out what's wrong with it.

```
if(this.props.mediaLoaded) {
            if(!this.props.currentTrack || this.props.currentTrack.id === '000') {
                this.props.setCurrentTrack(this.props.media[0]);
            }
```

**Comment by eff-society** [comment]
@Guichaguri Is there a way to detect when an audio file ends? Like any idea how should I go around doing something when an audio file finishes playing?

**Comment by Guichaguri** [comment]
There are the `playback-track-changed` and the `playback-queue-ended` events. You can read more about them in the [documentation](https://react-native-kit.github.io/react-native-track-player/documentation/#playback-track-changed)

**Comment by eff-society** [comment]
Thanks @Guichaguri . That helped a lot.
