### ISSUE TITLE
App crashes on call to TrackPlayer.remove(trackID)

### ISSUE THREAD

**Issue by GilVieira** [react-native-kit/react-native-track-player#515]
The application is crashing (android, I have not tested it on ios) when I try to remove the previous item from the one that is running, for example, I have the queue [track_1, track_2], track_2 is the current one when I try to remove the first item (`TrackPlayer.remove ('track_1_ID')`) The application hangs and closes. Debugging in Android Studio I received the following error:

```
2019-03-28 12:31:06.685 3699-3699/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 3699
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at java.util.Collections$SynchronizedList.get(Collections.java:2461)
        at com.guichaguri.trackplayer.service.player.ExoPlayback.onPositionDiscontinuity(ExoPlayback.java:209)
        at com.guichaguri.trackplayer.service.player.ExoPlayback.onTimelineChanged(ExoPlayback.java:200)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners(ExoPlayerImpl.java:771)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:708)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:639)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:584)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:125)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
Has anyone ever had this problem? tks...

**Comment by GilVieira** [comment]
Hi,

I include an index check on the remove method of the `LocalPlayback` class (line 109, before `queue.remove(index);`) and seems to be working fine.

The code:

```
if(index < lastKnownWindow) {
    lastKnownWindow = lastKnownWindow -1;
}
```

**Comment by roman-gula** [comment]
I have the same issue  on android and dev branch.

**Comment by roman-gula** [comment]
@Guichaguri I tried @GilVieira's solution and it works fine, please look at it, it seems to be easy fixed. Thanks!

**Comment by Guichaguri** [comment]
Sorry for taking too long to look into this. I've incorporated @GilVieira fix in https://github.com/react-native-kit/react-native-track-player/commit/8698cff09a7aa8f1b1b9e5b552ac591bb4b5cf56, thank you!
