### ISSUE TITLE
Galaxy S10 not working

### ISSUE THREAD

**Issue by sideokyou** [react-native-kit/react-native-track-player#534]
I tested on other Android devices and worked fine. but only Samsung Galaxy S10 is not working. After playing music, it crashes. Any idea what needs to be solved?

**Comment by Guichaguri** [comment]
Do you have any crash logs?

**Comment by ishigamii** [comment]
@Guichaguri I am having the same kind of report from user of Samsung Galaxy telling me that the sound is stopped as soon as the app goes in sleep mode (screen closing) it works if the screen is awake. 

For me I have this crash for user of (Galaxy S10+ and Galaxy S10e) : 
```
Fatal Exception: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: null
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1871)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7032)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by sideokyou** [comment]
![Screen Shot 2019-04-19 at 10 22 35 AM](https://user-images.githubusercontent.com/47291956/56435394-1690a600-628d-11e9-8e8c-53004658862f.png)


I am still figuring out why it shows this error on this device(galaxy s10) specifically.

I am not sure, but this error seems not related to react-native-track-player.  Commented all TextInput, and set all color properties as a static value such as #e2e2e2. Still showing this error.

Any help? 

Thank you in advance,
