### ISSUE TITLE
ProgressComponent not working

### ISSUE THREAD

**Issue by songoten28** [react-native-kit/react-native-track-player#641]
# Configuration

  Binaries:
    Node: 11.13.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.0
      System Images: android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.60.0-rc.2 => 0.60.0-rc.2

Version: 
    "react-native-swift": "^1.2.2",
    "react-native-track-player": "github:react-native-kit/react-native-track-player#dev",
    "react-redux": "^5.1.1",

"react-native-track-player" : 1.1.5 and 1.1.4 also got this problem
# Issue
Im not get any data from state of ProgressComponent
I already log 
this.state.position alway return `0`
this.state.duration alway return `0`

Another feature like Play(), Pause(), seekTo() is working ok.
# Code
index.js

````
TrackPlayer.registerEventHandler(eventHandler)
````

eventHandleer

````
export const eventHandler = async data => {
  let { play, pause } = mapDispatchToProps(store.dispatch)
  let position

  switch (data.type) {
    case 'remote-play':
      play()
      break
    case 'remote-pause':
      pause()
      break
    case 'remote-jump-forward':
      position = await TrackPlayer.getPosition()
      TrackPlayer.seekTo(position + JUMP_FORWARD_SECONDS)
      break
    case 'remote-jump-backward':
      position = await TrackPlayer.getPosition()
      TrackPlayer.seekTo(position - JUMP_BACK_SECONDS)
      break
    case 'remote-stop':
    case 'playback-queue-ended':
      TrackPlayer.seekTo(0)
      // pause()
      break
  }
}
````

````
 await TrackPlayer.setupPlayer()

    TrackPlayer.updateOptions({
      stopWithApp: true,
      maxArtworkSize: 600,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_JUMP_FORWARD,
        TrackPlayer.CAPABILITY_JUMP_BACKWARD,
        TrackPlayer.CAPABILITY_STOP,
        TrackPlayer.CAPABILITY_SEEK_TO,
      ],
      compactCapabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_JUMP_FORWARD,
        TrackPlayer.CAPABILITY_JUMP_BACKWARD,
        TrackPlayer.CAPABILITY_SEEK_TO,
      ],
    })

     const currentTrack = {
          id: "",
          url: "https://d2fj7ltie6ax01.cloudfront.net/2fb0c90169bf74f05f81f31fcb2f85acbf11c8d73a0309287c076c2fe6dce750.mp3",
          title: "",
          artist: "",
          artwork: "",
        }
     
        await TrackPlayer.add(currentTrack)
````

```
import React from 'react'
import { StyleSheet, Text, TouchableWithoutFeedback, View } from 'react-native'
import TrackPlayer, { ProgressComponent } from 'react-native-track-player'
import { formatTime } from '../util/trackPlayer'
import { ProgressBarView } from './ProgressBarView'
import connect from 'react-redux/es/connect/connect'
 class AudioProgressBar extends ProgressComponent {
  componentDidMount() {
    this.textColor = '#ffffff'
  }

  render() {
    if (this.props.textColor) {
      this.textColor = this.props.textColor
    }
    const position = formatTime(Math.floor(this.state.position))
    const remainTime = formatTime(
      Math.floor(this.state.duration - this.state.position)
    )
    let progress = this.getProgress() * 100

    const duration = this.state.duration > 0 ? this.state.duration : 0
    return (
      <ProgressBarView
        textColor={this.textColor}
        position={position}
        duration={duration}
        remainTime={remainTime}
        sliderChangedPosition={this.state.position}
        onValueChanged={value => TrackPlayer.seekTo(value)}
      />
    )
  }
}

const mapDispatchToProps = dispatch => ({
  play() {
    TrackPlayer.play()
    dispatch({ type: 'PLAY' })
  },
  pause() {
    TrackPlayer.pause()
    dispatch({ type: 'PAUSE' })
  },
})

export default connect(
  null,
  mapDispatchToProps
)(AudioProgressBar)```

//Logcat

2019-06-27 11:20:08.869 4548-4548/vn.music D/RNTrackPlayer: onPositionDiscontinuity: 2
2019-06-27 11:20:08.869 4548-4548/vn.music D/RNTrackPlayer: onStop
2019-06-27 11:20:08.872 4548-4548/vn.music D/RNTrackPlayer: onStateChange
2019-06-27 11:20:08.874 4548-4548/vn.music D/RNTrackPlayer: onEnd
2019-06-27 11:20:08.883 4548-4548/vn.music D/RNTrackPlayer: Preparing the media source...
2019-06-27 11:20:08.883 4548-4548/vn.music D/RNTrackPlayer: onPause
2019-06-27 11:20:08.884 4548-4578/vn.music E/zygote: No implementation found for com.facebook.react.bridge.Inspector com.facebook.react.bridge.Inspector.instance() (tried Java_com_facebook_react_bridge_Inspector_instance and Java_com_facebook_react_bridge_Inspector_instance__)
2019-06-27 11:20:08.885 4548-4578/vn.music E/unknown:ReactNative: Inspector doesn't work in open source yet
    java.lang.UnsatisfiedLinkError: No implementation found for com.facebook.react.bridge.Inspector com.facebook.react.bridge.Inspector.instance() (tried Java_com_facebook_react_bridge_Inspector_instance and Java_com_facebook_react_bridge_Inspector_instance__)
        at com.facebook.react.bridge.Inspector.instance(Native Method)
        at com.facebook.react.bridge.Inspector.getPages(Inspector.java:27)
        at com.facebook.react.devsupport.InspectorPackagerConnection.getPages(InspectorPackagerConnection.java:152)
        at com.facebook.react.devsupport.InspectorPackagerConnection.handleProxyMessage(InspectorPackagerConnection.java:72)
        at com.facebook.react.devsupport.InspectorPackagerConnection$Connection.onMessage(InspectorPackagerConnection.java:223)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

With ProcessComponent Both Platform Android and iOs not working..

**Comment by CyxouD** [comment]
I also experienced this issue. The issue is that we extend `TrackPlayer.ProgressComponent`, but it has its own logic in lifecycle methods. So, in `componentDidMount` the first line had to be `super.componentDidMount()` to call component's internal logic. (the same for `componentWillUnmount`)

**Comment by ajoykarmakar** [comment]
Still facing the issue. Is there any official documentation?

**Comment by jakecronin** [comment]
I got the issue solved using @CyxouD 's suggestion, but with the syntax: `super.componentDidMount?.apply(this);` as suggested on this [StackOverflow answer](https://stackoverflow.com/questions/31072841/componentdidmount-method-not-triggered-when-using-inherited-es6-react-class)
