### ISSUE TITLE
App is crashing on Android with v2.0.0-rc12

### ISSUE THREAD

**Issue by ithustle** [react-native-kit/react-native-track-player#668]
# Configuration

```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 21.16 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: ^0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

```
# Issue
After update to RNTP v2.0.0-rc12, I have this message on Logcat:

```
2019-07-13 20:52:34.528 10589-10589/com.toqueplay E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.toqueplay, PID: 10589
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.guichaguri.trackplayer.service.metadata.MetadataManager.updateOptions(MetadataManager.java:112)
        at com.guichaguri.trackplayer.service.MusicBinder.updateOptions(MusicBinder.java:45)
        at com.guichaguri.trackplayer.module.MusicModule.onServiceConnected(MusicModule.java:74)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1493)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1521)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6233)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by maikmacs** [comment]
I think this bug it's related to this one : https://github.com/react-native-kit/react-native-track-player/issues/665

**Comment by fcaride** [comment]
Yep thats my bug, the reason its the undefined constants of the library on Android

**Comment by dcvz** [comment]
@ithustle your issue comes from the fact that constants are now exporting differently. Please look at: https://github.com/react-native-kit/react-native-track-player/issues/662#issuecomment-511792143

**Comment by ithustle** [comment]
Thanks, @dcvz
