### ISSUE TITLE
taskProvider is not a function

### ISSUE THREAD

**Issue by rochapablo** [react-native-kit/react-native-track-player#675]
# Configuration

```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 503.98 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.10.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
```

What `react-native-track-player` version are you using?

```
"react": "16.8.6",
"react-native": "0.60.4",
"react-native-track-player": "^1.1.8",
```

# Issue
It was all working until I upgrade to the new RN version. Testing on Android device.

```
E/ReactNativeJS: taskProvider() is not a function. (In 'taskProvider()(data)', 'taskProvider()' is an instance of Promise)
```

# Code

**index.js**

```
import TrackPlayer from 'react-native-track-player';
import events from './src/services/player/events';

TrackPlayer.registerPlaybackService(events);
```

**events**

```
export default async () => {
  TrackPlayer.addEventListener('remote-play', onRemotePlay);
  TrackPlayer.addEventListener('remote-pause', onRemotePause);
  TrackPlayer.addEventListener('remote-stop', onRemoteStop);
  TrackPlayer.addEventListener('playback-state', onPlaybackState);
  TrackPlayer.addEventListener('playback-error', onPlaybackError);
};
```

**component**

```
class Player extends ProgressComponent<IProps, IState> {
  ...
}

export default connect(Ctrl.mapStateToProps, Ctrl.mapDispatchToProps)(Player);
```

**service**

```
export class PlayerService {
  public static async setupPlayer() {
    await TrackPlayer.setupPlayer({ waitForBuffer: true });

    TrackPlayer.updateOptions({
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_STOP,
      ],
    });

    TrackPlayer.setVolume(1); // 0.1 - 1
  }

  public static async toggle() {
    const state = await TrackPlayer.getState();
    if (state === TrackPlayer.STATE_PLAYING) {
      await TrackPlayer.pause();
    } else if (state === TrackPlayer.STATE_PAUSED) {
      await play();
    } else if (state === TrackPlayer.STATE_STOPPED) {
      await play();
    }
  }
}
```

**[UPDATE]**

doing

```
export default () => {
  return async () => {
    TrackPlayer.addEventListener('remote-play', onRemotePlay);
    ...
  };
};
```

it stops the error, but the remote controls doesn't work

**Comment by rochapablo** [comment]
Sometimes I'm also getting

```
E/ActivityThread: Service com.guichaguri.trackplayer.service.MusicService has leaked IntentReceiver com.guichaguri.trackplayer.service.MusicManager$1@19ee55c that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Service com.guichaguri.trackplayer.service.MusicService has leaked IntentReceiver com.guichaguri.trackplayer.service.MusicManager$1@19ee55c that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1348)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1115)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1405)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1378)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1366)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:614)
        at com.guichaguri.trackplayer.service.MusicManager.onPlay(MusicManager.java:150)
        at com.guichaguri.trackplayer.service.player.ExoPlayback.onPlayerStateChanged(ExoPlayback.java:294)
        at com.guichaguri.trackplayer.service.player.LocalPlayback.onPlayerStateChanged(LocalPlayback.java:192)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$setPlayWhenReady$0(ExoPlayerImpl.java:254)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$OKMPvkXpqXeKaJZFBZ8m9YfNXpE.invokeListener(Unknown Source:4)
        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:165)
        at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:823)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$notifyListeners$6(ExoPlayerImpl.java:716)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$DrcaME6RvvSdC72wmoYPUB4uP5w.run(Unknown Source:4)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:726)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:716)
        at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:254)
        at com.google.android.exoplayer2.SimpleExoPlayer.updatePlayWhenReady(SimpleExoPlayer.java:1224)
        at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:921)
        at com.guichaguri.trackplayer.service.player.ExoPlayback.play(ExoPlayback.java:134)
        at com.guichaguri.trackplayer.service.player.LocalPlayback.play(LocalPlayback.java:150)
        at com.guichaguri.trackplayer.module.MusicModule.lambda$play$10$MusicModule(MusicModule.java:316)
        at com.guichaguri.trackplayer.module.-$$Lambda$MusicModule$6tPjSgn9zq8na8C_MNqG23hrTLw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6595)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by YajanaRao** [comment]
@rochapablo 
Similar configaration is working for me in "react-native-track-player": "^1.2.0". 
You can refer the Project https://github.com/YajanaRao/Serenity

**Comment by Guichaguri** [comment]
You're supposed to have
```js
TrackPlayer.registerPlaybackService(() => events);
```
and not
```js
TrackPlayer.registerPlaybackService(events);
```

**Comment by laurpantelimon** [comment]
I am following the installation guide but still receive the "[TypeError: taskProvider() is not a function. (In 'taskProvider()(data)', 'taskProvider()' is undefined)" error. In the index.js I have "TrackPlayer.registerPlaybackService(() => { require("./service"); });" after AppRegistry.
