### ISSUE TITLE
[@next, v2] NullPointerException - Cannot play any audio

### ISSUE THREAD

**Issue by illestrater** [react-native-kit/react-native-track-player#731]
# Configuration

System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 3.56 GB / 15.94 GB
  Binaries:
    Node: 8.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      Android NDK: 18.1.5063045
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501

What `react-native-track-player` version are you using?
@next, v2.0-rc13

# Issue
I'm using this module perfectly fine before React Native v0.60+ / AndroidX. But after performing all necessary upgrades, I'm getting this crash.
```
2019-09-09 23:14:25.091 10603-10603/com.cuenative E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cuenative, PID: 10603
    java.lang.RuntimeException: Unable to start service com.guichaguri.trackplayer.service.MusicService@d507ef8 with Intent { cmp=com.cuenative/com.guichaguri.trackplayer.service.MusicService }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setFlags(int)' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setFlags(int)' on a null object reference
        at com.guichaguri.trackplayer.service.metadata.MetadataManager.<init>(MetadataManager.java:76)
        at com.guichaguri.trackplayer.service.MusicManager.<init>(MusicManager.java:68)
        at com.guichaguri.trackplayer.service.MusicService.onStartCommand(MusicService.java:111)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by rsokz** [comment]
+1

**Comment by Guichaguri** [comment]
Can you test 764b48df703f185d65106aacc54d3db00529a557 to see if it fixes the issue?

**Comment by Guichaguri** [comment]
I'll be closing this for inactivity. Feel free to reopen it if you're still experiencing the issue.

**Comment by troublediehard** [comment]
@Guichaguri does it make sense to cherry-pick it in V2?
