### ISSUE TITLE
Android crashing after updating targetSdkVersion to 28

### ISSUE THREAD

**Issue by CharlesCarey** [react-native-kit/react-native-track-player#733]
# Configuration
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 418.00 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4

    "react-native-track-player": "1.1.3",

*Note*: No matter what version of react-native-track-player we try, it always seems to crash.

# Issue
After updating our app's targetSdkVersion to 28, the app reliably crashes on opening in a production build, with a development build it will only crash sometimes.

With targetSdkVersion 26 everything is fine.

This is the output of the error from running adb logcat:
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://68.168.103.13:8264/;
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at java.lang.Thread.run(Thread.java:764)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal: Caused by: java.io.IOException: Cleartext HTTP traffic to 68.168.103.13 not permitted
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:444)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
09-11 23:31:45.994 13128 13213 E ExoPlayerImplInternal:         ... 6 more
09-11 23:31:45.995 13128 13128 D RNTrackPlayer: onError
09-11 23:31:45.995 13128 13128 E RNTrackPlayer: Playback error: playback-source - Unable to connect to http://68.168.103.13:8264/;
09-11 23:31:45.998 13128 13201 E ReactNativeJS: 'error', { message: 'Unable to connect to http://68.168.103.13:8264/;',
09-11 23:31:45.998 13128 13201 E ReactNativeJS:   code: 'playback-source' }
09-11 23:31:46.004 13128 13202 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
09-11 23:31:46.004 13128 13202 E AndroidRuntime: Process: com.radiocult, PID: 13128
09-11 23:31:46.004 13128 13202 E AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: lineNumber
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:128)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:182)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
09-11 23:31:46.004 13128 13202 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
09-11 23:31:46.005  1853  2481 W ActivityManager:   Force finishing activity

I suspect the logs about being unable to connect to the stream are not too relevant, as the android emulator is very unreliable about connecting to external streams. I suspect the real issue is something to do with the AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException stuff.

**Comment by CharlesCarey** [comment]
Turns out the error was unrelated. It was fixed by following the instructions here https://stackoverflow.com/questions/55576030/react-native-android-error-in-com-facebook-react-bridge-nosuchkeyexception

The react native track player related logs were a red herring. Sorry to waste any time!
