### ISSUE TITLE
App crashes when run on android but fine on IOS w/expo kit.

### ISSUE THREAD

**Issue by missionary1995** [react-native-kit/react-native-track-player#885]
I got react-native-track-player with expo kit (ejected) to work fine on IOS. The problem is when i run it on android the app crashes and i get this error message. If expo is the issue, i really dont want to remove expo kit as i like some of the features it offers. Does anyone know of any solution to get this to work. PLEASE HELP ME!

    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: Woerthship.V3, PID: 10219
    java.lang.RuntimeException: Unable to start service com.guichaguri.trackplayer.service.MusicService@e1ec6f7 with Intent { cmp=Woerthship.V3/com.guichaguri.trackplayer.service.MusicService }: java.lang.ClassCastException: host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassCastException: host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at com.facebook.react.HeadlessJsTaskService.getReactNativeHost(HeadlessJsTaskService.java:166)
        at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:97)
        at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:48)
        at com.guichaguri.trackplayer.service.MusicService.onStartCommand(MusicService.java:114)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Guichaguri** [comment]
As [stated in the installation instructions](https://react-native-track-player.js.org/install/#expo-and-expokit-support), Expo is not supported due to it removing essential react-native features that allow this module to run on Android. Sorry

**Comment by fierysolid** [comment]
This issue has nothing to do with expokit, I also get this issue and I wasn't in Expo to begin with.
